<html>
<head>
    <title>Index</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">

</head>
<body>

<div>
    <div class="container">

        <h1>Tasks</h1>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Task</th>
                <th>Status</th>
            </tr>
            </thead>
            <tbody id="table-body">
            <?php
            if (!empty($tasks)) {
                foreach ($tasks as $task) {
                    ?>
                    <tr class="table-row">
                        <td><?= $task["name"]; ?></td>
                        <td><?= $task["email"]; ?></td>
                        <td><?= $task["task"]; ?></td>
                        <td><?= $task["status"]; ?> </td>
                    </tr>
                    <?php
                }
            }
            ?>
            </tbody>
        </table>
    </div>

    <div class="container">
        <p>
        <form action="/addtask/tasks/">
            <button type="submit">add Task</button>
        </p>


        <?php
        if (!empty($countItems)) {
            for ($i = 1; $i <= $countItems; $i++) { ?>
                <a href="?page=<?= $i; ?>"><?= $i; ?></a>
                <?php
            }
        }
        ?>
    </div>


</div>
</body>
</html>